pipeline {
  agent none
  stages {
    stage('Test') {
      agent {
        docker {
          image 'qnib/pytest'
        }
      }
      steps {
        sh 'py.test --verbose --junit-xml tests/results.xml chatbot/chat.py'
      }
      post {
        always {
          junit 'tests/results.xml'
        }
      }
    }
    stage('Build') {
      agent any
      steps {
        sh 'docker build -t ccawmu-${BUILD_NUMBER} .'
      }
    }
    stage('Deploy') {
      agent any
      steps {
        sh 'docker run ccawmu-${BUILD_NUMBER}'
      }
    }
  }
}